### ISSUE TITLE
Suppress traces on liveness and readiness probes

### ISSUE THREAD

**Issue by msg-theism** [msgoat/cnj-tracing#2]
Right now, in the showcases using MicroProfile and Quarkus, ALL requests are traced including the liveness and readiness probes invoked by Kubernetes. Annotation  @Traced(false) on ProbesResource class does not seem to work. Try to find other ways to suppress request tracing of irrelevant requests (like probes).

**Comment by Traced** [comment]
您好，我看到以后就回复您
